// layout.tsx
import type { Metadata } from "next";
import { Azeret_Mono } from "next/font/google";
import "./globals.css";
import { PropsWithChildren } from "react";

const azeret = Azeret_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = PropsWithChildren<{
  dialog?: React.ReactNode;
}>;

export default function RootLayout({ children, dialog }: Props) {
  return (
    <html lang="en">
      <body className={azeret.className}>
        <div className="relative">{children}</div>
        {dialog && <div>{dialog}</div>}
      </body>
    </html>
  );
}
